### ISSUE TITLE
Application Tracking

### ISSUE THREAD

**Issue by armintalaie** [ubclaunchpad/CosmicGateway#3]
Implement the application tracking page UI

- [ ] `/portal/applications` page
- [ ] Change application status
  - [ ] Withdraw, Decline or Accept (on applicant side)
  - [ ] Update application by admin/lead 
  - [ ] Connect to patch method for API

Bonus
- [ ] Send an email on final application status types (`accepted`, `declined`, `rejected`, and `withdrawn`)
